### ISSUE TITLE
DOM Standard (Jun 2019) review tracker

### ISSUE THREAD

**Issue by LJWatson** [w3c/htmlwg#4]
#### Requested
- [x] [APA WG requested 8 Aug](https://lists.w3.org/Archives/Public/public-apa/2019Aug/0011.html)
- [x] [HTML WG requested 8 Aug](https://lists.w3.org/Archives/Public/public-html/2019Aug/0001.html)
- [x] [I18n IG requested 8 Aug](https://lists.w3.org/Archives/Public/www-international/2019JulSep/0053.html)
- [x] [Privacy IG requested 8 Aug](https://lists.w3.org/Archives/Public/public-privacy/2019JulSep/0026.html)
- [x] [TAG requested 8 Aug](https://github.com/w3ctag/design-reviews/issues/404#issuecomment-519995822)
- [x] [W3C Chairs (member only) requested 8 Aug](https://lists.w3.org/Archives/Member/chairs/2019JulSep/0029.html)
- [x] [WebApps WG requested 8 Aug](https://lists.w3.org/Archives/Public/public-webapps/2019JulSep/0013.html)
- [x] [Web Security requested 8 Aug](https://lists.w3.org/Archives/Public/public-web-security/2019Aug/0000.html)

#### Responses
* [ ] [I18n](https://github.com/w3c/i18n-activity/issues/727)
* [x] [Privacy: WHATWG issue #777](https://github.com/whatwg/dom/issues/777)
* [x] [Security: WHATWG issue #776](https://github.com/whatwg/dom/issues/776)
* [x] [TAG](https://github.com/w3ctag/design-reviews/issues/404#issuecomment-519995822)
