### ISSUE TITLE
HTML Standard (Jul 2019): review tracker

### ISSUE THREAD

**Issue by LJWatson** [w3c/htmlwg#5]
#### Requested
* [x] [APA WG requested 30 Aug](https://lists.w3.org/Archives/Public/public-apa/2019Aug/0077.html)
* [x] [HTML WG requested 30 Aug](https://lists.w3.org/Archives/Public/public-html/2019Aug/0006.html)
* [x] [I18n WG requested on 30 Aug](https://lists.w3.org/Archives/Public/www-international/2019JulSep/0088.html)
* [x] [Privacy IG requested on 20 Aug](https://lists.w3.org/Archives/Public/public-privacy/2019JulSep/0041.html)
* [x] [TAG](https://github.com/w3ctag/design-reviews/issues/412)
* [x] [W3C Chairs (member only) requested 30 Aug](https://lists.w3.org/Archives/Member/chairs/2019JulSep/0049.html)
* [x] [WebApps WG requested on 30 Aug](https://lists.w3.org/Archives/Public/public-webapps/2019JulSep/0020.html)
* [x] [Web Security IG requested on 30 Aug](https://lists.w3.org/Archives/Public/public-web-security/2019Aug/0004.html)

#### Responses
TBC.

**Comment by LJWatson** [comment]
@siusin  did you ask the TAG and Privacy IG for review?

**Comment by siusin** [comment]
@LJWatson yes we did :)

**Comment by matatk** [comment]
#### APA Review Results

We reported the following two potential concerns/minor comments (with follow-up to happen on both), but neither are significant issues, certainly not showstoppers. They both turned out to be minor things, so APA has no official concerns.

* Concern: [focusability of `<audio>` and `<video>`](https://github.com/whatwg/html/issues/5087)
* Comment (with minor issue to follow): [question about the accessibility of navigation occuring in the `opener` of a pop-up window](https://github.com/whatwg/html/pull/4330#issuecomment-548994450).

##### Background info

* [Background info on my review and process suggestions](https://lists.w3.org/Archives/Public/public-apa/2019Nov/0000.html).
* [Other things we may like to follow in future](https://lists.w3.org/Archives/Public/public-apa/2019Nov/0003.html) (item 1 in that post became the "concern" issue above)

##### Updates

**2019-11-07:** As per the latest conversation on the HTML PR thread linked above, I'll be filing a new issue on the behaviour of pop-ups in due course, but as the accessibility concern we have was not introduced by the latest changes to HTML and is somewhat esoteric, I don't think it should hold up the CR process.

**2019-11-13:** [On the APA call today we discussed one of the potential issues I'd raised and decided that it was a concern as it appears to leave a gap in the spec](https://www.w3.org/2019/11/13-apa-minutes.html#item05); I will file an issue about this tomorrow and update this comment to point to it. 

**2019-11-15:** Added the "concern" issue mentioned above.

**2019-12-04:** Updated to state [we have no concerns as per today's APA meeting](https://www.w3.org/2019/12/04-apa-minutes.html#item06).
