### ISSUE TITLE
HTML Standard (Jan 2020): review tracker

### ISSUE THREAD

**Issue by siusin** [w3c/htmlwg#8]
## Requested
- [x] [APA WG](https://lists.w3.org/Archives/Public/public-apa/2020Apr/0022.html)
- [ ] [HTML WG](https://lists.w3.org/Archives/Public/public-html/2020Apr/0002.html)
- [x] [I18n WG](https://lists.w3.org/Archives/Public/www-international/2020AprJun/0021.html)
- [x] [Privacy IG](https://lists.w3.org/Archives/Public/public-privacy/2020AprJun/)([no concern 2020-04-21](https://lists.w3.org/Archives/Member/chairs/2020AprJun/0030.html))
- [x] [TAG](https://github.com/w3ctag/design-reviews/issues/499)
- [x] [W3C Chairs](https://lists.w3.org/Archives/Member/chairs/2020AprJun/0023.html)
- [ ] [WebApps WG](https://lists.w3.org/Archives/Public/public-webapps/2020AprJun/0000.html) 
- [ ] [Web Security IG](https://lists.w3.org/Archives/Public/public-web-security/2020Apr/0002.html)

### Accessibility?

* [Further `tabIndex` getter tweaks](https://github.com/whatwg/html/pull/4759)
* [Make the default `tabIndex` for `<frame>` 0](https://github.com/whatwg/html/pull/4859)
* [Make `autofocus=""` a global attribute](https://github.com/whatwg/html/pull/4830)
* [Update autofocus processing algorithm](https://github.com/whatwg/html/pull/4763)
* [Update sequential focus navigation to include shadow trees](https://github.com/whatwg/html/pull/4735)
* [Define different types of focusability](https://github.com/whatwg/html/pull/4768)
* [Handle delegates focus in the focusing steps](https://github.com/whatwg/html/pull/4796)
* [Tweak shadow host focus delegation](https://github.com/whatwg/html/pull/5039)
* [Prevent double-focusing with `autofocus=""` inside `<dialog>`](https://github.com/whatwg/html/pull/4918)
* [Make `autofocus=""` work with `delegatesFocus` and `<area>`](https://github.com/whatwg/html/pull/5059)
* [Add Accessibility considerations to element definitions](https://github.com/whatwg/html/pull/5077)
* [Add Accessibility considerations for custom elements](https://github.com/whatwg/html/pull/5171)

### I18N?

* [Do not inherit text-transform (et al.) on form controls](https://github.com/whatwg/html/pull/4672)

### Security?

* [Fix conformance requirements on `<script>`'s `integrity=""` attribute](https://github.com/whatwg/html/pull/4843)
* [Revert addition of JSON modules](https://github.com/whatwg/html/pull/4943)
* [Define (schemelessly) same site for origins](https://github.com/whatwg/html/pull/5076)
* [Restrict (un)registerProtocolHandler to secure contexts](https://github.com/whatwg/html/pull/5080)
* [Snapshot sandbox at the start of navigation](https://github.com/whatwg/html/pull/5098)
* [Give browsing context an explicit container](https://github.com/whatwg/html/pull/5091)
* [Only run "perform a security check" for `Window` and `Location` objects ](https://github.com/whatwg/html/pull/5141)
* [Disallow serializing and transferring non-origin-clean `ImageBitmap`](https://github.com/whatwg/html/pull/5114)

### Privacy?

* [Explicitly prevent sandboxed navigation via History](https://github.com/whatwg/html/pull/4787)

### Architecture?

* [Make `<img>.complete` more reliable](https://github.com/whatwg/html/pull/4934)
* [Change default value of `window.open()`'s `url` argument](https://github.com/whatwg/html/pull/4851)
* [Remove `<img>` progress events](https://github.com/whatwg/html/pull/4842)
* [Define `DocumentOrShadowRoot`'s `activeElement`](https://github.com/whatwg/html/pull/4837)
* [Imperatively allocate window agents and agent clusters](https://github.com/whatwg/html/pull/4617)
* [Update all constructors, including `HTMLConstructor`](https://github.com/whatwg/html/pull/4915)
* [Specify which event loop to use for posting messages](https://github.com/whatwg/html/pull/4917)
* [Use width and height as intrinsic aspect ratio for img elements](https://github.com/whatwg/html/pull/4952)
* [Make window.window/frames/self deal with no browsing context](https://github.com/whatwg/html/pull/4410))
* [Ignore document.open/write after the active parser has been aborted](https://github.com/whatwg/html/pull/4907)
* [Change the timing of "flush autofocus candidates”](https://github.com/whatwg/html/pull/5015)
* [Introduce `SubmitEvent` for the form `submit` event](https://github.com/whatwg/html/pull/4984)
* [Revamp the user activation model](https://github.com/whatwg/html/pull/3851)
* [Add "queue an element task” algorithm](https://github.com/whatwg/html/pull/5072)
* [Define `getSVGDocument()` in terms of content document](https://github.com/whatwg/html/pull/5109)
* [Cleanups to "execute a script block” Signpost the debate on some script mismatches](https://github.com/whatwg/html/pull/5154)
* [Move the `DOMParser` class to HTML](https://github.com/whatwg/html/pull/5190)

**Comment by hober** [comment]
It would be helpful to change each list item to be a link to the actual issue. I'll try to do this later today when I have time.

**Comment by hober** [comment]
The TAG's review is complete: w3ctag/design-reviews#499

**Comment by matatk** [comment]
The Accessible Platform Architectures (APA) group's review is complete, with no concerns to be raised. [[APA meeting minutes]](https://www.w3.org/2020/05/13-apa-minutes.html#item07)

There have been several positive changes that relate to, and may raise awareness of, accessibility recently, including [the inclusion of accessibility considerations](https://github.com/whatwg/html/pull/5077) and [clarifications on focusability](https://github.com/whatwg/html/commit/1ab7c860) and [label activation behaviour](https://github.com/whatwg/html/commit/836294cb).

I attached a summary of review results both for the PRs highlighted above, and for the other commits during the review timeframe, to my [results email to the APA list](https://lists.w3.org/Archives/Public/public-apa/2020May/0014.html) in case you would like any background details.

**Comment by aphillips** [comment]
The I18N WG's review is complete and we are satisfied that the new snapshot does not introduce any new issues.

Resolution: https://www.w3.org/2020/05/21-i18n-minutes.html
Tracked at: https://github.com/w3c/i18n-request/issues/113

We continue to work with the WHATWG on [open issues](https://github.com/w3c/i18n-activity/issues?q=is%3Aissue+is%3Aopen+label%3As%3Ahtml+label%3Aneeds-resolution) in the HTML and related specifications. 
[[I18N-ACTION-913](https://www.w3.org/International/track/actions/913)]
